name: SkypixleTab
version: 5.0.2
author: AydenC77
main: me.neznamy.tab.bridge.bukkit.BukkitBridge
api-version: 1.13
website: "https://github.com/NEZNAMY/TAB-Bridge"
softdepend: [PlaceholderAPI, Vault]
description: "Extends features when TAB is installed on BungeeCord"
folia-supported: true